[pytest]
pythonpath = .
testpaths = tests

# Общие правила поиска тестов
python_files = test*.py *_test.py tests.py
python_classes = Test*
python_functions = test_*

# Глобальные опции pytest
addopts =
    --verbose
    --tb=short
    --disable-warnings
    --ignore-glob=___*
    --ignore-glob=*/___*
